language: node_js
# fix to workaround node/jest incompatibility https://github.com/facebook/jest/issues/8069.
node_js:
  - 8

stages:
  - name: after_success
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

before_install:
  - node --version
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

install:
  - yarn install
  - yarn list

script:
  - yarn test

after_success:
  - npx semantic-release@beta
  - yarn run jest --coverage --coverageReporters=text-lcov | yarn run coveralls # report coveralls status

before_deploy:
  - yarn build:storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: ./storybook-static
  on:
    branch: master
